Update patch set 1
Patch Set 1:

https://trunk.rdoproject.org/fedora/61/37/6137a69cbcfa28a13b98a1b457e2497c438e3170_73b5716d/rpmbuild.log

  DEBUG: Running Sphinx v1.6.5
  DEBUG: making output directory...
  DEBUG: connecting events for openstackdocstheme
  DEBUG: BUILDSTDERR: Exception occurred:
  DEBUG: BUILDSTDERR:   File "/usr/lib/python3.6/site-packages/sphinx_feature_classification/support_matrix.py", line 486, in setup
  DEBUG: BUILDSTDERR:     app.add_css_file('support-matrix.css')
  DEBUG: BUILDSTDERR: AttributeError: 'Sphinx' object has no attribute 'add_css_file'
  DEBUG: BUILDSTDERR: The full traceback has been saved in /tmp/sphinx-err-th5qg9_1.log, if you want to report the issue to the developers.
  DEBUG: BUILDSTDERR: Please also report this if it was a user error, so that a better error message can be 
provided next time.
  DEBUG: BUILDSTDERR: A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
  DEBUG: BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.Zm30jZ (%install)
  DEBUG: BUILDSTDERR:     Bad exit status from /var/tmp/rpm-tmp.Zm30jZ (%install)

Stephen, We don't set an upper constraint anywhere for sphinx AFAICT, maybe we need to?

https://github.com/rdo-packages/placement-distgit/blob/73b5716d9ce4761e6fd1ab69f82a856655d68b7e/openstack-placement.spec#L171-L174

Patch-set: 1
Reviewer: Gerrit User 142 <142@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Workflow=0